default: &default
  adapter: postgresql
  username: vitaly
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: top_app

production:
  <<: *default
  database: toy_app

test:
  <<: *default
  database: toy_app_test
